add extra catches to scripts

diff --git a/docs/tutorials/convert_notebooks b/docs/tutorials/convert_notebooks
--- a/docs/tutorials/convert_notebooks
+++ b/docs/tutorials/convert_notebooks
@@ -1,6 +1,7 @@
-#!/bin/bash
+#!/usr/bin/env bash
 # Convert Quarto notebooks to Jupyter notebooks
 # (although note that they can be run in Jupyter directly via jupytext)
+set -euo pipefail # Fail fast if needed
 
 for f in *.qmd; do
     quarto convert "$f"
